from .delete_user import DeleteUser
from .edit_jogo import EditJogo
from .find_byemail import FindUserByEmail
from .list_jogo import ListJogos
from .login_user import LoginUser
from .register_jogo import RegisterJogo
from .register_user import RegisterUser
from .remove_jogo import RemoveJogo
from .update_user import UpdateUser